DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS notebooks CASCADE;
DROP TABLE IF EXISTS meta_contents CASCADE;
DROP TABLE IF EXISTS nodes_contents CASCADE;
DROP TABLE IF EXISTS meta_tag_contents CASCADE;
DROP TABLE IF EXISTS tags CASCADE;